//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TARS.DataModel.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        public int DonorId { get; set; }
        public string FullName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string BankName { get; set; }
        public decimal TransationAmount { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string TransactionId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> DonorStatus { get; set; }
        public string DonorFor { get; set; }
        public string DonatingFor { get; set; }
    }
}
