//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TARS.DataModel.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TARSEntities : DbContext
    {
        public TARSEntities()
            : base("name=TARSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Donor> Donors { get; set; }
        public virtual DbSet<Lga> Lgas { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserClaim> UserClaims { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<Victim> Victims { get; set; }
        public virtual DbSet<VictimPhoto> VictimPhotoes { get; set; }
        public virtual DbSet<VictimPercentageRate> VictimPercentageRates { get; set; }
        public virtual DbSet<VictimProfile> VictimProfiles { get; set; }
        public virtual DbSet<VictimPhotoPercentage> VictimPhotoPercentages { get; set; }
    }
}
