//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TARS.DataModel.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VictimPhoto
    {
        public int PhotoId { get; set; }
        public string PhotoTitle { get; set; }
        public string PhotoUrl { get; set; }
        public int VictimId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> PhotoStatus { get; set; }
    
        public virtual Victim Victim { get; set; }
    }
}
