//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TARS.DataModel.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VictimPercentageRate
    {
        public int VictimId { get; set; }
        public Nullable<int> percentageProfile { get; set; }
        public Nullable<int> PercentageSum { get; set; }
        public Nullable<bool> VictimStatus { get; set; }
    }
}
